name: Build Dart SDK RPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools

      - name: Add depot_tools to PATH
        run: echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build build-essential rpm
          sudo gem install fpm

      - name: Sync dependencies
        run: gclient sync

      - name: Build Dart SDK
        run: python3 tools/build.py -m release -a x64 create_sdk

      - name: Create RPM package
        run: python3 tools/linux_dist_support/create_rpm_package.py --sdk_dir out/ReleaseX64/dart-sdk --out_dir rpm_output

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v3
        with:
          name: dart-sdk-rpm
          path: rpm_output/*.rpm
